// Mock data for development — replace with real DB calls
export const mockHorses = [
  {
    id: "h1",
    name: "Valeria W",
    breed: "KWPN",
    age: 7,
    gender: "MARE",
    color: "Bay",
    heightCm: 168,
    country: "Netherlands",
    sire: "Vivaldi",
    dam: "Ulrike W",
    discipline: "Dressage",
    category: "ELITE_SPORT",
    description:
      "A breathtaking KWPN mare with exceptional gaits and outstanding rideability. Valeria W has competed successfully at Grand Prix level and is a genuine 10-mover. Her three gaits are of the highest quality, and she has a winning mentality that sets her apart. Already proven at international level with multiple top-3 placings. This mare represents a once-in-a-decade opportunity for the serious Grand Prix rider.",
    startingPrice: 280000,
    currentPrice: 320000,
    currency: "EUR",
    vetChecked: true,
    featured: true,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=1200&q=90",
      "https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=1200&q=90",
      "https://images.unsplash.com/photo-1534773728080-33d31da27ae5?w=1200&q=90",
    ]),
    videoUrl: null,
    auctionId: "a1",
    bids: [
      { id: "b1", amount: 280000, userId: "u2", createdAt: new Date("2026-06-18T10:00:00Z") },
      { id: "b2", amount: 300000, userId: "u3", createdAt: new Date("2026-06-19T14:30:00Z") },
      { id: "b3", amount: 320000, userId: "u2", createdAt: new Date("2026-06-20T09:15:00Z") },
    ],
  },
  {
    id: "h2",
    name: "Don Royale",
    breed: "Hanoverian",
    age: 5,
    gender: "STALLION",
    color: "Dark Bay",
    heightCm: 172,
    country: "Germany",
    sire: "Desperados FRH",
    dam: "Dolce Vita",
    discipline: "Dressage",
    category: "FUTURE_STARS",
    description:
      "An extraordinary young stallion with three world-class gaits and an incredible work ethic. Don Royale is by the legendary Desperados FRH and shows all the hallmarks of a future Grand Prix champion. His walk is a 10, his trot groundcovers the arena with exceptional suspension, and his canter is pure quality. This is a rare investment opportunity in a horse with limitless potential.",
    startingPrice: 95000,
    currentPrice: 145000,
    currency: "EUR",
    vetChecked: true,
    featured: true,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=1200&q=90",
      "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=1200&q=90",
    ]),
    videoUrl: null,
    auctionId: "a1",
    bids: [
      { id: "b4", amount: 95000, userId: "u3", createdAt: new Date("2026-06-17T11:00:00Z") },
      { id: "b5", amount: 120000, userId: "u1", createdAt: new Date("2026-06-19T16:45:00Z") },
      { id: "b6", amount: 145000, userId: "u3", createdAt: new Date("2026-06-20T11:20:00Z") },
    ],
  },
  {
    id: "h3",
    name: "Spartacus Z",
    breed: "Zangersheide",
    age: 9,
    gender: "GELDING",
    color: "Grey",
    heightCm: 175,
    country: "Belgium",
    sire: "Sheraton",
    dam: "Una Z",
    discipline: "Show Jumping",
    category: "ELITE_SPORT",
    description:
      "A proven 1.50m+ international show jumper with an exceptional record at Grand Prix level. Spartacus Z has competed at CSIO 5* events across Europe and the Americas with multiple winning rounds. He is careful, brave, and has a natural ability to read distances. An honest competitor that any professional rider would be proud to represent at the highest level.",
    startingPrice: 350000,
    currentPrice: 420000,
    currency: "EUR",
    vetChecked: true,
    featured: true,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1534773728080-33d31da27ae5?w=1200&q=90",
      "https://images.unsplash.com/photo-1573246123716-6b1782bfc499?w=1200&q=90",
    ]),
    videoUrl: null,
    auctionId: "a1",
    bids: [
      { id: "b7", amount: 350000, userId: "u1", createdAt: new Date("2026-06-16T09:00:00Z") },
      { id: "b8", amount: 390000, userId: "u2", createdAt: new Date("2026-06-18T14:00:00Z") },
      { id: "b9", amount: 420000, userId: "u1", createdAt: new Date("2026-06-20T17:30:00Z") },
    ],
  },
  {
    id: "h4",
    name: "Floriana",
    breed: "Oldenburg",
    age: 12,
    gender: "MARE",
    color: "Chestnut",
    heightCm: 165,
    country: "Germany",
    sire: "Fürst Romancier",
    dam: "Lady Florence",
    discipline: "Breeding",
    category: "BREEDING_INVESTMENT",
    description:
      "A premium Oldenburg broodmare with flawless bloodlines and an impeccable breeding record. Floriana has produced four licensed offspring, two of which have competed at international level. Her pedigree combines the best of modern Oldenburg breeding with proven sport genetics. An exceptional investment for any serious breeding program.",
    startingPrice: 45000,
    currentPrice: 62000,
    currency: "EUR",
    vetChecked: true,
    featured: false,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=1200&q=90",
      "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=1200&q=90",
    ]),
    videoUrl: null,
    auctionId: "a1",
    bids: [
      { id: "b10", amount: 45000, userId: "u2", createdAt: new Date("2026-06-19T10:00:00Z") },
      { id: "b11", amount: 62000, userId: "u3", createdAt: new Date("2026-06-20T13:00:00Z") },
    ],
  },
  {
    id: "h5",
    name: "Casino Royal V",
    breed: "Belgian Warmblood",
    age: 6,
    gender: "STALLION",
    color: "Bay",
    heightCm: 170,
    country: "Belgium",
    sire: "Canturo",
    dam: "Radina V",
    discipline: "Show Jumping",
    category: "COMPETITION_READY",
    description:
      "A spectacular 6-year-old BWP stallion ready to compete at 1.40–1.45m level. Casino Royal V has exceptional scope, a fantastic mind, and a powerful engine. He has been produced by one of Belgium's top yards and is ready to step up to the big league immediately. His bascule and technique over fences is exceptional — a horse that can reach the very top.",
    startingPrice: 75000,
    currentPrice: 98000,
    currency: "EUR",
    vetChecked: true,
    featured: false,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1573246123716-6b1782bfc499?w=1200&q=90",
      "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=1200&q=90",
    ]),
    videoUrl: null,
    auctionId: "a2",
    bids: [
      { id: "b12", amount: 75000, userId: "u1", createdAt: new Date("2026-06-20T08:00:00Z") },
      { id: "b13", amount: 98000, userId: "u2", createdAt: new Date("2026-06-21T09:30:00Z") },
    ],
  },
  {
    id: "h6",
    name: "Estrella Negra",
    breed: "PRE (Andalusian)",
    age: 8,
    gender: "MARE",
    color: "Black",
    heightCm: 162,
    country: "Spain",
    sire: "Emboscado IV",
    dam: "Noche Oscura",
    discipline: "Dressage / Working Equitation",
    category: "COMPETITION_READY",
    description:
      "A stunning pure PRE mare with exceptional movement and the classic baroque beauty of the Spanish horse. Estrella Negra has competed at Prix St. Georges level and is also schooled in Working Equitation. Her expressive trot and powerful piaffe make her a standout performer. An extraordinary opportunity to acquire one of the finest PRE mares on the market.",
    startingPrice: 55000,
    currentPrice: 78000,
    currency: "EUR",
    vetChecked: true,
    featured: false,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=1200&q=90",
      "https://images.unsplash.com/photo-1534773728080-33d31da27ae5?w=1200&q=90",
    ]),
    videoUrl: null,
    auctionId: "a2",
    bids: [
      { id: "b14", amount: 55000, userId: "u3", createdAt: new Date("2026-06-20T12:00:00Z") },
      { id: "b15", amount: 78000, userId: "u1", createdAt: new Date("2026-06-21T07:45:00Z") },
    ],
  },
];

export const mockAuctions = [
  {
    id: "a1",
    title: "Summer Elite Collection 2026",
    description:
      "Our most prestigious collection to date — 24 hand-selected horses representing the pinnacle of global sport horse breeding. From elite Grand Prix competitors to future stars, this collection defines the global standard.",
    startDate: new Date("2026-06-15T10:00:00Z"),
    endDate: new Date("2026-06-28T20:00:00Z"),
    status: "LIVE",
    featured: true,
    coverImage:
      "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=1600&q=90",
    horses: mockHorses.filter((h) => h.auctionId === "a1"),
  },
  {
    id: "a2",
    title: "International Sport Horse Auction — July 2026",
    description:
      "A carefully curated selection of international sport horses from Belgium, Spain, Germany, and the Netherlands. Competition-ready horses and future stars for riders of every ambition.",
    startDate: new Date("2026-07-05T10:00:00Z"),
    endDate: new Date("2026-07-15T20:00:00Z"),
    status: "UPCOMING",
    featured: false,
    coverImage:
      "https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=1600&q=90",
    horses: mockHorses.filter((h) => h.auctionId === "a2"),
  },
];

export const mockUser = {
  id: "u1",
  email: "info@glasspyramid.com",
  name: "Gianni Doncarlo",
  country: "Italy",
  phone: "+39 02 1234 5678",
  role: "BIDDER",
  bids: [
    { id: "b9", amount: 420000, currency: "EUR", horseId: "h3", horse: mockHorses[2], createdAt: new Date("2026-06-20T17:30:00Z") },
    { id: "b6", amount: 145000, currency: "EUR", horseId: "h2", horse: mockHorses[1], createdAt: new Date("2026-06-20T11:20:00Z") },
    { id: "b12", amount: 75000, currency: "EUR", horseId: "h5", horse: mockHorses[4], createdAt: new Date("2026-06-20T08:00:00Z") },
  ],
  watchlist: [
    { horse: mockHorses[0] },
    { horse: mockHorses[2] },
  ],
};
